(function(){
'use strict';
var state={token:localStorage.getItem('ai_academy_session')||'',user:null,route:'',dashboard:null,course:null,currentLesson:null,postOffset:0,platforms:[]};
var routeMeta={dashboard:['Tổng quan','Tiếp tục hành trình xây doanh nghiệp tự động'],'my-courses':['Khóa học của tôi','Tất cả khóa học bạn đang được mở quyền'],course:['Lộ trình học','Học theo Level và mở khóa từng Module'],community:['Community','Cùng học, cùng làm và cùng tiến bộ'],notifications:['Thông báo','Các cập nhật mới nhất dành cho bạn'],profile:['Hồ sơ cá nhân','Thông tin tài khoản và bảo mật'],admin:['Dashboard Admin','Tổng quan hoạt động hệ thống'],'admin-submissions':['Duyệt bài','Đánh giá bài thực hành của học viên'],'admin-students':['Quản lý học viên','Tài khoản, XP và quyền truy cập'],'admin-courses':['Quản lý khóa học','Level, Module và bài học'],'admin-platforms':['Kênh & API','Quản lý Apps Script API URL và các nền tảng kéo traffic']};

function gas(name){
  var args=[].slice.call(arguments,1);
  var apiUrl=String(window.AI_ACADEMY_API_URL||'').trim();
  if(!apiUrl||apiUrl.indexOf('PASTE_')>=0){return Promise.reject(new Error('Chưa cấu hình AI_ACADEMY_API_URL trong config.js.'));}
  return fetch(apiUrl,{
    method:'POST',
    headers:{'Content-Type':'text/plain;charset=utf-8'},
    body:JSON.stringify({action:name,args:args}),
    redirect:'follow'
  }).then(function(response){
    if(!response.ok) throw new Error('HTTP '+response.status);
    return response.text();
  }).then(function(text){
    try{return JSON.parse(text);}
    catch(error){throw new Error('Apps Script không trả JSON hợp lệ. Kiểm tra URL /exec và quyền deploy.');}
  }).catch(function(error){
    throw new Error('Không gọi được Apps Script API. Kiểm tra config.js, deploy Web App và quyền truy cập. Chi tiết: '+error.message);
  });
}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char];});}
function safeUrl(value){var text=String(value||'');return /^https?:\/\//i.test(text)?text:'#';}
function platformIcon(label){var name=String(label||'').toLowerCase();if(name.indexOf('tiktok')>=0)return'♪';if(name.indexOf('facebook')>=0)return'f';if(name.indexOf('zalo')>=0)return'Z';if(name.indexOf('thread')>=0)return'@';if(name==='x'||name.indexOf('twitter')>=0)return'𝕏';if(name.indexOf('youtube')>=0)return'▶';if(name.indexOf('whop')>=0)return'W';if(name.indexOf('skool')>=0)return'S';return'↗';}
function renderPlatformLinks(container,items,compact){if(!container)return;var enabled=(items||state.platforms||[]).filter(function(item){return item.public!==false&&item.value&&/^https?:\/\//i.test(item.value);});container.innerHTML='';container.classList.toggle('hidden',!enabled.length);if(!enabled.length){container.innerHTML='<p class="muted">Chưa cấu hình kênh cộng đồng.</p>';return;}enabled.forEach(function(item){var link=document.createElement('a');link.href=safeUrl(item.value);link.target='_blank';link.rel='noopener';link.className='platform-link '+(compact?'compact':'');link.innerHTML='<span>'+esc(platformIcon(item.label))+'</span><strong>'+esc(item.label)+'</strong>';container.appendChild(link);});}
function template(id){return document.getElementById(id).content.cloneNode(true);}
function rootLoading(){var root=document.getElementById('view-root');root.innerHTML='';root.appendChild(template('loading-template'));}
function toast(message,type){var item=document.createElement('div');item.className='toast '+(type||'');item.textContent=message;document.getElementById('toast-root').appendChild(item);setTimeout(function(){item.remove();},3500);}
function apiError(response){if(response&&['SESSION_INVALID','SESSION_EXPIRED','ACCOUNT_INACTIVE'].indexOf(response.code)>=0){logoutLocal();toast('Phiên đăng nhập đã hết hạn.','error');}throw new Error(response&&response.message?response.message:'Không thể xử lý yêu cầu.');}
function assertApi(response){if(!response||!response.success)apiError(response);return response.data;}
function firstName(name){return String(name||'Bạn').trim().split(/\s+/).slice(-1)[0];}
function formatDate(value){if(!value)return'';var date=new Date(value);return isNaN(date)?String(value):date.toLocaleString('vi-VN');}
function setButtonBusy(button,busy,label){if(!button)return;if(busy){button.dataset.label=button.textContent;button.disabled=true;button.textContent=label||'Đang xử lý…';}else{button.disabled=false;button.textContent=button.dataset.label||button.textContent;}}
function showLogin(){document.getElementById('app-loading').classList.add('hidden');document.getElementById('app-shell').classList.add('hidden');document.getElementById('login-view').classList.remove('hidden');}
function showApp(){document.getElementById('app-loading').classList.add('hidden');document.getElementById('login-view').classList.add('hidden');document.getElementById('app-shell').classList.remove('hidden');updateUserChrome();}
function logoutLocal(){state.token='';state.user=null;localStorage.removeItem('ai_academy_session');showLogin();}
function updateUserChrome(){if(!state.user)return;document.getElementById('sidebar-name').textContent=state.user.fullName;document.getElementById('sidebar-role').textContent=state.user.role;document.getElementById('sidebar-avatar').textContent=firstName(state.user.fullName).charAt(0).toUpperCase();document.getElementById('xp-chip').textContent='⚡ '+Number(state.user.totalXP||0)+' XP';document.getElementById('admin-nav').classList.toggle('hidden',state.user.role!=='ADMIN');document.getElementById('student-nav').classList.toggle('hidden',state.user.role==='ADMIN');document.querySelector('.mobile-nav').classList.toggle('hidden',state.user.role==='ADMIN');}
function bindRoutes(scope){(scope||document).querySelectorAll('[data-route]').forEach(function(button){button.addEventListener('click',function(){navigate(button.dataset.route);});});}
function navigate(route,params){params=params||{};if(route.indexOf('admin')===0&&(!state.user||state.user.role!=='ADMIN'))route='dashboard';state.route=route;document.querySelectorAll('[data-route]').forEach(function(button){button.classList.toggle('active',button.dataset.route===route);});var meta=routeMeta[route]||routeMeta.dashboard;document.getElementById('page-title').textContent=meta[0];document.getElementById('page-subtitle').textContent=meta[1];document.querySelector('.sidebar').classList.remove('open');rootLoading();var loaders={dashboard:loadDashboard,'my-courses':loadMyCourses,course:function(){return loadCourse(params.courseId);},lesson:function(){return loadLesson(params.lessonId);},community:loadCommunity,notifications:loadNotifications,profile:loadProfile,admin:loadAdminDashboard,'admin-submissions':loadAdminSubmissions,'admin-students':loadAdminStudents,'admin-courses':loadAdminCourses,'admin-platforms':loadAdminPlatforms};Promise.resolve((loaders[route]||loadDashboard)()).catch(renderError);}
function renderError(error){var root=document.getElementById('view-root');root.innerHTML='';var fragment=template('error-template');fragment.querySelector('.error-message').textContent=error.message||String(error);fragment.querySelector('[data-action="retry"]').addEventListener('click',function(){navigate(state.route||'dashboard');});root.appendChild(fragment);}
function confirmAction(title,message){return new Promise(function(resolve){var modal=document.getElementById('confirm-modal');document.getElementById('confirm-title').textContent=title;document.getElementById('confirm-message').textContent=message;modal.classList.remove('hidden');function done(value){modal.classList.add('hidden');ok.onclick=null;cancel.onclick=null;resolve(value);}var ok=document.getElementById('confirm-ok'),cancel=document.getElementById('confirm-cancel');ok.onclick=function(){done(true);};cancel.onclick=function(){done(false);};});}

async function loadPublicPlatforms(){try{var data=assertApi(await gas('getPublicPlatformSettings'));state.platforms=data.items||[];renderPlatformLinks(document.getElementById('login-platform-links'),state.platforms,true);}catch(ignore){}}
async function bootstrap(){bindGlobal();await loadPublicPlatforms();if(!state.token){showLogin();return;}try{var data=assertApi(await gas('authGetSession',state.token));state.user=data.user;showApp();if(state.user.mustChangePassword){document.getElementById('password-modal').classList.remove('hidden');return;}navigate(window.APP_INITIAL_VIEW|| (state.user.role==='ADMIN'?'admin':'dashboard'));}catch(error){logoutLocal();}}
function bindGlobal(){bindRoutes(document);document.getElementById('mobile-menu-button').onclick=function(){document.querySelector('.sidebar').classList.toggle('open');};document.getElementById('logout-button').onclick=async function(){try{await gas('authLogout',state.token);}catch(ignore){}logoutLocal();};document.getElementById('login-form').addEventListener('submit',login);document.getElementById('password-form').addEventListener('submit',changePassword);document.getElementById('password-modal-close').onclick=function(){if(state.user&&!state.user.mustChangePassword)document.getElementById('password-modal').classList.add('hidden');};}
async function login(event){event.preventDefault();var form=event.currentTarget,button=form.querySelector('button[type="submit"]'),errorBox=document.getElementById('login-error');errorBox.classList.add('hidden');setButtonBusy(button,true,'Đang đăng nhập…');try{var values=Object.fromEntries(new FormData(form).entries());values.userAgent=navigator.userAgent;var data=assertApi(await gas('authLogin',values));state.token=data.sessionToken;state.user=data.user;localStorage.setItem('ai_academy_session',state.token);showApp();if(state.user.mustChangePassword)document.getElementById('password-modal').classList.remove('hidden');else navigate(state.user.role==='ADMIN'?'admin':'dashboard');}catch(error){errorBox.textContent=error.message;errorBox.classList.remove('hidden');}finally{setButtonBusy(button,false);}}
async function changePassword(event){event.preventDefault();var form=event.currentTarget,button=form.querySelector('button');setButtonBusy(button,true);try{var payload=Object.fromEntries(new FormData(form).entries());payload.userAgent=navigator.userAgent;var data=assertApi(await gas('authChangePassword',state.token,payload));state.token=data.sessionToken;state.user=data.user;localStorage.setItem('ai_academy_session',state.token);document.getElementById('password-modal').classList.add('hidden');toast('Đổi mật khẩu thành công.','success');updateUserChrome();navigate(state.user.role==='ADMIN'?'admin':'dashboard');}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}}

async function loadDashboard(){var data=assertApi(await gas('getStudentDashboard',state.token));state.dashboard=data;state.course=data.course;state.user=data.user;updateUserChrome();var root=document.getElementById('view-root'),fragment=template('dashboard-template');function text(field,value){fragment.querySelector('[data-field="'+field+'"]').textContent=value;}text('firstName',firstName(data.user.fullName));text('progressPercent',data.stats.percent+'%');text('totalXP',data.user.totalXP);text('completedLessons',data.stats.completedLessons+'/'+data.stats.totalLessons);text('pendingSubmissions',data.pendingSubmissions);text('badgeCount',data.badges.length);text('courseName',data.course.courseName);fragment.querySelector('[data-field="progressBar"]').style.width=data.stats.percent+'%';fragment.querySelector('[data-action="continue-learning"]').disabled=!data.continueLesson;fragment.querySelector('[data-action="continue-learning"]').addEventListener('click',function(){if(data.continueLesson)navigate('lesson',{lessonId:data.continueLesson.lessonId});});var levels=fragment.querySelector('#dashboard-levels');data.course.levels.forEach(function(level){var modules=level.modules,total=modules.length,done=modules.filter(function(item){return item.status==='COMPLETED';}).length;levels.insertAdjacentHTML('beforeend','<div class="mini-level '+(done===total&&total?'done':'')+'">'+esc(level.levelName)+'<br><strong>'+done+'/'+total+' Module</strong></div>');});var leaderboard=fragment.querySelector('#dashboard-leaderboard');data.leaderboard.slice(0,5).forEach(function(item){leaderboard.insertAdjacentHTML('beforeend','<div class="leader-row"><span class="leader-rank">#'+item.rank+'</span><div class="avatar">'+esc(firstName(item.fullName).charAt(0))+'</div><span>'+esc(item.fullName)+'</span><strong>⚡ '+item.totalXP+'</strong></div>');});var badges=fragment.querySelector('#dashboard-badges');if(!data.badges.length)badges.innerHTML='<p class="muted">Hoàn thành bài học để nhận huy hiệu đầu tiên.</p>';data.badges.forEach(function(item){badges.insertAdjacentHTML('beforeend','<div class="badge-item"><div class="badge-icon">◆</div><small>'+esc(item.badgeName)+'</small></div>');});var notices=fragment.querySelector('#dashboard-notifications');if(!data.notifications.length)notices.innerHTML='<p>Không có thông báo mới.</p>';data.notifications.forEach(function(item){notices.insertAdjacentHTML('beforeend','<div class="simple-row"><span>♢</span><div><strong>'+esc(item.title)+'</strong><small>'+esc(item.message)+'</small></div></div>');});renderPlatformLinks(fragment.querySelector('#dashboard-platform-links'),state.platforms,false);root.innerHTML='';root.appendChild(fragment);bindRoutes(root);}

async function loadMyCourses(){var data=assertApi(await gas('getMyCourses',state.token)),root=document.getElementById('view-root'),fragment=template('my-courses-template'),list=fragment.querySelector('#my-course-list');if(!data.items.length){list.innerHTML='<div class="state-card"><h3>Bạn chưa được mở khóa học nào</h3><p>Liên hệ admin để được cấp quyền học.</p></div>';}data.items.forEach(function(course){var card=document.createElement('article');card.className='course-pick-card';card.innerHTML='<span class="eyebrow">KHÓA HỌC</span><h3>'+esc(course.courseName)+'</h3><p>'+esc(course.description||'')+'</p><div class="progress-track"><div class="progress-fill" style="width:'+esc(course.stats.percent)+'%"></div></div><small>'+esc(course.stats.completedLessons)+'/'+esc(course.stats.totalLessons)+' bài · '+esc(course.stats.percent)+'% hoàn thành</small><div class="row-actions"><button class="primary-button">Vào lộ trình</button>'+(course.continueLesson?'<button class="ghost-button">Học tiếp</button>':'')+'</div>';card.querySelector('.primary-button').onclick=function(){navigate('course',{courseId:course.courseId});};var next=card.querySelector('.ghost-button');if(next)next.onclick=function(){navigate('lesson',{lessonId:course.continueLesson.lessonId});};list.appendChild(card);});root.innerHTML='';root.appendChild(fragment);}

async function loadCourse(courseId){var response=await gas('getCourseMap',state.token,courseId||state.course&&state.course.courseId||'');var data=assertApi(response);state.course=data;var completed=0,total=0;data.levels.forEach(function(level){level.modules.forEach(function(module){module.lessons.forEach(function(lesson){total++;if(lesson.status==='COMPLETED')completed++;});});});var percent=total?Math.round(completed*100/total):0,root=document.getElementById('view-root'),fragment=template('course-template');fragment.querySelector('[data-field="courseName"]').textContent=data.courseName;fragment.querySelector('[data-field="courseDescription"]').textContent=data.description;fragment.querySelector('[data-field="coursePercent"]').textContent=percent+'%';var stack=fragment.querySelector('#course-levels');data.levels.forEach(function(level){var levelNode=document.createElement('article');levelNode.className='level-card';levelNode.innerHTML='<div class="level-title"><div><span class="eyebrow">LEVEL '+esc(level.sortOrder)+'</span><h3>'+esc(level.levelName)+'</h3></div><span>'+esc(level.description||'')+'</span></div>';level.modules.forEach(function(module){var moduleNode=document.createElement('div');moduleNode.className='module-card';moduleNode.innerHTML='<div class="module-title"><div><strong>'+esc(module.moduleName)+'</strong><p>'+esc(module.description||'')+'</p></div><span class="status-pill '+esc(module.status)+'">'+esc(module.status)+'</span></div><div class="lesson-list"></div>';var list=moduleNode.querySelector('.lesson-list');module.lessons.forEach(function(lesson){var button=document.createElement('button');button.className='lesson-row';button.disabled=lesson.status==='LOCKED';button.innerHTML='<span>'+(lesson.status==='COMPLETED'?'✓':lesson.status==='LOCKED'?'🔒':'▶')+'</span><div><strong>'+esc(lesson.lessonName)+'</strong><small>'+esc(lesson.description||'')+'</small></div><span class="lesson-xp">⚡ '+lesson.xpReward+'</span>';button.addEventListener('click',function(){navigate('lesson',{lessonId:lesson.lessonId});});list.appendChild(button);});levelNode.appendChild(moduleNode);});stack.appendChild(levelNode);});root.innerHTML='';root.appendChild(fragment);bindRoutes(root);}

function youtubeEmbed(url){var match=String(url||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([A-Za-z0-9_-]{6,})/);return match?'https://www.youtube.com/embed/'+match[1]:'';}
async function loadLesson(lessonId){if(!lessonId){navigate('course');return;}var data=assertApi(await gas('getLessonDetail',state.token,lessonId));state.currentLesson=data;var root=document.getElementById('view-root'),fragment=template('lesson-template');fragment.querySelector('[data-field="breadcrumb"]').textContent=(data.level?data.level.levelName:'')+' / '+(data.module?data.module.moduleName:'');fragment.querySelector('[data-field="lessonName"]').textContent=data.lessonName;fragment.querySelector('[data-field="lessonDescription"]').textContent=data.description;fragment.querySelector('[data-field="xpReward"]').textContent=data.xpReward+' XP';fragment.querySelector('#lesson-content').innerHTML=data.contentHtml||'<p>Nội dung đang được cập nhật.</p>';var embed=youtubeEmbed(data.youtubeUrl);if(embed){var video=fragment.querySelector('#lesson-video');video.classList.remove('hidden');video.innerHTML='<iframe src="'+esc(embed)+'" allowfullscreen loading="lazy"></iframe>';}if(data.resourceUrl)fragment.querySelector('#lesson-resources').innerHTML='<p><a class="ghost-button" href="'+esc(safeUrl(data.resourceUrl))+'" target="_blank" rel="noopener">Mở tài liệu học tập ↗</a></p>';var checklist=fragment.querySelector('#lesson-checklist');(Array.isArray(data.checklist)?data.checklist:[]).forEach(function(item){checklist.insertAdjacentHTML('beforeend','<div class="check-item">□ '+esc(typeof item==='string'?item:item.text||'')+'</div>');});var status=fragment.querySelector('#submission-status'),form=fragment.querySelector('#submission-form'),action=fragment.querySelector('#lesson-action');if(data.requiresSubmission){var latest=data.latestSubmission;if(latest)status.innerHTML='<div class="submission-status-card"><span class="status-pill '+esc(latest.status)+'">'+esc(latest.status)+'</span><p>Nộp lúc: '+esc(formatDate(latest.submittedAt))+'</p>'+(latest.feedback?'<p><strong>Nhận xét:</strong> '+esc(latest.feedback)+'</p>':'')+'</div>';if(!latest||latest.status==='NEEDS_REVISION')form.classList.remove('hidden');form.addEventListener('submit',submitAssignment);}else if(data.status!=='COMPLETED'){action.innerHTML='<button id="complete-lesson" class="primary-button">Đánh dấu hoàn thành</button>';action.querySelector('button').onclick=completeCurrentLesson;}else action.innerHTML='<div class="submission-status-card"><span class="status-pill COMPLETED">✓ ĐÃ HOÀN THÀNH</span></div>';root.innerHTML='';root.appendChild(fragment);bindRoutes(root);}
async function submitAssignment(event){event.preventDefault();var button=event.currentTarget.querySelector('button'),payload=Object.fromEntries(new FormData(event.currentTarget).entries());payload.lessonId=state.currentLesson.lessonId;setButtonBusy(button,true);try{assertApi(await gas('submitLessonAssignment',state.token,payload));toast('Nộp bài thành công.','success');loadLesson(payload.lessonId);}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}}
async function completeCurrentLesson(event){var button=event.currentTarget;setButtonBusy(button,true);try{var data=assertApi(await gas('completeLesson',state.token,state.currentLesson.lessonId));toast(data.xp.awarded?'Hoàn thành! +'+data.xp.amount+' XP':'Đã hoàn thành bài học.','success');state.course=null;loadLesson(state.currentLesson.lessonId);}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}}

async function loadCommunity(){state.postOffset=0;var root=document.getElementById('view-root'),fragment=template('community-template');var guide=fragment.querySelector('.community-guide');if(guide){guide.insertAdjacentHTML('beforeend','<hr><h3>Kênh bên ngoài</h3><div id="community-platform-links" class="platform-links"></div>');renderPlatformLinks(guide.querySelector('#community-platform-links'),state.platforms,false);}root.innerHTML='';root.appendChild(fragment);root.querySelector('#post-form').addEventListener('submit',createPost);root.querySelector('#load-more-posts').onclick=loadMorePosts;await loadMorePosts();}
async function loadMorePosts(){var data=assertApi(await gas('getCommunityPosts',state.token,{offset:state.postOffset,limit:10}));var list=document.getElementById('post-list');data.posts.forEach(function(post){list.appendChild(renderPost(post));});state.postOffset=data.nextOffset;document.getElementById('load-more-posts').classList.toggle('hidden',data.nextOffset==null);if(!list.children.length)list.innerHTML='<div class="state-card"><h3>Chưa có bài viết</h3><p>Hãy là người đầu tiên chia sẻ.</p></div>';}
function renderPost(post){var card=document.createElement('article');card.className='post-card';card.dataset.postId=post.postId;card.innerHTML='<div class="post-author"><div class="avatar">'+esc(firstName(post.author.fullName).charAt(0))+'</div><div><strong>'+esc(post.author.fullName)+'</strong><small>'+esc(formatDate(post.createdAt))+'</small></div></div><p class="post-content">'+esc(post.content)+'</p>'+(post.linkUrl?'<p><a href="'+esc(safeUrl(post.linkUrl))+'" target="_blank" rel="noopener">'+esc(post.linkUrl)+'</a></p>':'')+'<div class="post-actions"><button data-action="like" class="'+(post.likedByMe?'liked':'')+'">♥ <span>'+post.likeCount+'</span></button><button data-action="comments">💬 '+post.commentCount+'</button>'+(post.canEdit?'<button data-action="edit">Sửa</button>':'')+(post.canDelete?'<button data-action="delete">Xóa</button>':'')+'</div><div class="comments-box hidden"></div>';card.querySelector('[data-action="like"]').onclick=async function(event){try{var data=assertApi(await gas('togglePostLike',state.token,post.postId));event.currentTarget.classList.toggle('liked',data.liked);event.currentTarget.querySelector('span').textContent=data.likeCount;}catch(error){toast(error.message,'error');}};card.querySelector('[data-action="comments"]').onclick=function(){toggleComments(card,post.postId);};var editButton=card.querySelector('[data-action="edit"]');if(editButton)editButton.onclick=async function(){var content=prompt('Chỉnh sửa bài viết:',post.content);if(content===null||!content.trim())return;try{var updated=assertApi(await gas('updateCommunityPost',state.token,post.postId,{content:content,linkUrl:post.linkUrl||''}));card.replaceWith(renderPost(updated));toast('Đã cập nhật bài viết.','success');}catch(error){toast(error.message,'error');}};var deleteButton=card.querySelector('[data-action="delete"]');if(deleteButton)deleteButton.onclick=async function(){if(await confirmAction('Xóa bài viết','Bạn chắc chắn muốn xóa bài viết này?')){try{assertApi(await gas('deleteCommunityPost',state.token,post.postId));card.remove();toast('Đã xóa bài viết.','success');}catch(error){toast(error.message,'error');}}};return card;}
async function toggleComments(card,postId){var box=card.querySelector('.comments-box');if(!box.classList.contains('hidden')){box.classList.add('hidden');return;}box.classList.remove('hidden');box.innerHTML='<p>Đang tải…</p>';try{var items=assertApi(await gas('getPostComments',state.token,postId));box.innerHTML='';items.forEach(function(item){var row=document.createElement('div');row.className='simple-row';row.innerHTML='<div><strong>'+esc(item.author?item.author.fullName:'Thành viên')+'</strong><p>'+esc(item.content)+'</p></div>'+(item.canDelete?'<button class="ghost-button">Xóa</button>':'');var button=row.querySelector('button');if(button)button.onclick=async function(){try{assertApi(await gas('deletePostComment',state.token,item.commentId));row.remove();}catch(error){toast(error.message,'error');}};box.appendChild(row);});box.insertAdjacentHTML('beforeend','<form class="compose-footer"><input name="content" maxlength="1000" required placeholder="Viết bình luận…"><button class="primary-button">Gửi</button></form>');box.querySelector('form').onsubmit=async function(event){event.preventDefault();var input=event.currentTarget.elements.content,button=event.currentTarget.querySelector('button');setButtonBusy(button,true);try{assertApi(await gas('createPostComment',state.token,postId,input.value));await toggleComments(card,postId);await toggleComments(card,postId);}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}};}catch(error){box.textContent=error.message;}}
async function createPost(event){event.preventDefault();var button=event.currentTarget.querySelector('button'),payload=Object.fromEntries(new FormData(event.currentTarget).entries());setButtonBusy(button,true);try{var post=assertApi(await gas('createCommunityPost',state.token,payload));var list=document.getElementById('post-list');if(list.querySelector('.state-card'))list.innerHTML='';list.prepend(renderPost(post));event.currentTarget.reset();toast('Đã đăng bài.','success');}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}}

async function loadNotifications(){var data=assertApi(await gas('getNotifications',state.token,{limit:100})),root=document.getElementById('view-root'),fragment=template('notifications-template'),list=fragment.querySelector('#notification-list');if(!data.items.length)list.innerHTML='<div class="state-card"><h3>Bạn chưa có thông báo</h3></div>';data.items.forEach(function(item){var row=document.createElement('div');row.className='notification-row '+(item.isRead?'':'unread');row.innerHTML='<span>♢</span><div><strong>'+esc(item.title)+'</strong><p>'+esc(item.message)+'</p><small>'+esc(formatDate(item.createdAt))+'</small></div>';if(!item.isRead)row.onclick=async function(){try{assertApi(await gas('markNotificationRead',state.token,item.notificationId));row.classList.remove('unread');}catch(error){toast(error.message,'error');}};list.appendChild(row);});fragment.querySelector('#mark-all-read').onclick=async function(){try{assertApi(await gas('markAllNotificationsRead',state.token));loadNotifications();}catch(error){toast(error.message,'error');}};root.innerHTML='';root.appendChild(fragment);updateNotificationBadge(data.unreadCount);}
function updateNotificationBadge(count){var badge=document.getElementById('notification-badge');badge.textContent=count;badge.classList.toggle('hidden',!count);}

async function loadProfile(){var data=assertApi(await gas('getMyProfile',state.token)),root=document.getElementById('view-root'),fragment=template('profile-template'),form=fragment.querySelector('#profile-form');form.elements.fullName.value=data.fullName||'';form.elements.email.value=data.email||'';form.elements.phone.value=data.phone||'';form.elements.avatarUrl.value=data.avatarUrl||'';form.elements.hideFromLeaderboard.checked=Boolean(data.hideFromLeaderboard);form.onsubmit=async function(event){event.preventDefault();var button=form.querySelector('button'),payload=Object.fromEntries(new FormData(form).entries());payload.hideFromLeaderboard=form.elements.hideFromLeaderboard.checked;setButtonBusy(button,true);try{var updated=assertApi(await gas('updateMyProfile',state.token,payload));state.user=updated;updateUserChrome();toast('Đã cập nhật hồ sơ.','success');}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}};fragment.querySelector('#open-password-modal').onclick=function(){document.getElementById('password-form').reset();document.getElementById('password-modal').classList.remove('hidden');};root.innerHTML='';root.appendChild(fragment);}

async function loadAdminDashboard(){var data=assertApi(await gas('adminGetDashboard',state.token)),root=document.getElementById('view-root'),fragment=template('admin-dashboard-template'),stats=fragment.querySelector('#admin-stats');[['♙',data.totalStudents,'HỌC VIÊN'],['✓',data.pendingSubmissions,'CHỜ DUYỆT'],['◫',data.activeEnrollments,'GHI DANH'],['◎',data.communityPosts,'BÀI COMMUNITY']].forEach(function(item){stats.insertAdjacentHTML('beforeend','<article class="stat-card"><span>'+item[0]+'</span><div><strong>'+item[1]+'</strong><small>'+item[2]+'</small></div></article>');});fragment.querySelector('#announcement-form').onsubmit=async function(event){event.preventDefault();var button=event.currentTarget.querySelector('button');setButtonBusy(button,true);try{var result=assertApi(await gas('adminPostAnnouncement',state.token,Object.fromEntries(new FormData(event.currentTarget).entries())));toast('Đã gửi tới '+result.recipients+' học viên.','success');event.currentTarget.reset();}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}};fragment.querySelector('#test-telegram').onclick=async function(event){setButtonBusy(event.currentTarget,true);try{assertApi(await gas('testTelegramNotification',state.token));toast('Telegram hoạt động tốt.','success');}catch(error){toast(error.message,'error');}finally{setButtonBusy(event.currentTarget,false);}};fragment.querySelector('#badge-form').onsubmit=async function(event){event.preventDefault();var button=event.currentTarget.querySelector('button'),payload=Object.fromEntries(new FormData(event.currentTarget).entries());setButtonBusy(button,true);try{assertApi(await gas('adminSaveBadge',state.token,payload));toast('Đã tạo huy hiệu.','success');event.currentTarget.reset();}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}};root.innerHTML='';root.appendChild(fragment);}

async function loadAdminSubmissions(){var root=document.getElementById('view-root'),fragment=template('admin-submissions-template');root.innerHTML='';root.appendChild(fragment);root.querySelector('#submission-filter').onchange=refreshAdminSubmissions;root.querySelector('.modal-close').onclick=function(){document.getElementById('review-modal').classList.add('hidden');};root.querySelector('#review-form').onsubmit=reviewSubmission;await refreshAdminSubmissions();}
async function refreshAdminSubmissions(){var filter=document.getElementById('submission-filter'),status=filter?filter.value:'PENDING',data=assertApi(await gas('adminListSubmissions',state.token,{status:status,limit:100})),list=document.getElementById('admin-submission-list');list.innerHTML='';if(!data.items.length){list.innerHTML='<div class="state-card"><h3>Không có bài nộp</h3></div>';return;}data.items.forEach(function(item){var row=document.createElement('div');row.className='admin-list-row';row.innerHTML='<div><strong>'+esc(item.student?item.student.fullName:'Học viên')+'</strong><small>'+esc(item.student?item.student.email:'')+'</small></div><div><strong>'+esc(item.lesson?item.lesson.lessonName:'Bài học')+'</strong><small>'+esc(formatDate(item.submittedAt))+'</small></div><div class="row-actions"><span class="status-pill '+esc(item.status)+'">'+esc(item.status)+'</span><button class="ghost-button">Chi tiết</button></div>';row.querySelector('button').onclick=function(){openReview(item);};list.appendChild(row);});}
function openReview(item){var modal=document.getElementById('review-modal');modal.dataset.submissionId=item.submissionId;document.getElementById('review-detail').innerHTML='<p><strong>Học viên:</strong> '+esc(item.student?item.student.fullName:'')+'</p><p><strong>Bài học:</strong> '+esc(item.lesson?item.lesson.lessonName:'')+'</p><p><strong>Ghi chú:</strong> '+esc(item.note||'Không có')+'</p><p><a href="'+esc(safeUrl(item.submissionUrl))+'" target="_blank" rel="noopener">Mở bài làm ↗</a></p>';document.getElementById('review-form').elements.feedback.value=item.feedback||'';modal.classList.remove('hidden');}
async function reviewSubmission(event){event.preventDefault();var submitter=event.submitter,payload={submissionId:document.getElementById('review-modal').dataset.submissionId,decision:submitter.value,feedback:event.currentTarget.elements.feedback.value};setButtonBusy(submitter,true);try{assertApi(await gas('adminReviewSubmission',state.token,payload));document.getElementById('review-modal').classList.add('hidden');toast(payload.decision==='APPROVED'?'Đã duyệt bài.':'Đã yêu cầu làm lại.','success');refreshAdminSubmissions();}catch(error){toast(error.message,'error');}finally{setButtonBusy(submitter,false);}}

async function loadAdminStudents(){var data=assertApi(await gas('adminListStudents',state.token,{})),root=document.getElementById('view-root'),fragment=template('admin-students-template');root.innerHTML='';root.appendChild(fragment);renderStudents(data);root.querySelector('#student-search').oninput=function(event){var query=event.target.value.toLowerCase();renderStudents(data.filter(function(user){return user.fullName.toLowerCase().includes(query)||user.email.toLowerCase().includes(query);}));};}
function renderStudents(users){var list=document.getElementById('admin-student-list');list.innerHTML='';users.forEach(function(user){var row=document.createElement('div');row.className='admin-list-row';row.innerHTML='<div><strong>'+esc(user.fullName)+'</strong><small>'+esc(user.email)+' · '+esc(user.phone||'Chưa có SĐT')+'</small></div><div><strong>⚡ '+user.totalXP+' XP</strong><small>'+user.enrollments.length+' khóa học</small></div><div class="row-actions"><select data-action="status"><option value="ACTIVE">ACTIVE</option><option value="LOCKED">LOCKED</option><option value="DISABLED">DISABLED</option></select><button data-action="xp" class="ghost-button">XP</button><button data-action="unlock" class="ghost-button">Mở Module</button><button data-action="badge" class="ghost-button">Cấp huy hiệu</button></div>';row.querySelector('select').value=user.status;row.querySelector('select').onchange=async function(event){try{assertApi(await gas('adminSetStudentStatus',state.token,user.userId,event.target.value));toast('Đã cập nhật trạng thái.','success');}catch(error){toast(error.message,'error');}};row.querySelector('[data-action="xp"]').onclick=async function(){var amount=prompt('Nhập số XP cần cộng hoặc trừ (ví dụ 50 hoặc -20):');if(amount===null)return;var reason=prompt('Lý do điều chỉnh XP:');if(!reason)return;try{assertApi(await gas('adminAdjustXp',state.token,{userId:user.userId,amount:Number(amount),reason:reason}));toast('Đã điều chỉnh XP.','success');loadAdminStudents();}catch(error){toast(error.message,'error');}};row.querySelector('[data-action="unlock"]').onclick=async function(){var moduleId=prompt('Nhập moduleId cần mở khóa:');if(!moduleId)return;try{assertApi(await gas('adminUnlockModule',state.token,{userId:user.userId,moduleId:moduleId}));toast('Đã mở khóa Module.','success');}catch(error){toast(error.message,'error');}};row.querySelector('[data-action="badge"]').onclick=async function(){var badgeId=prompt('Nhập badgeId cần cấp:');if(!badgeId)return;try{assertApi(await gas('adminAwardBadge',state.token,{userId:user.userId,badgeId:badgeId}));toast('Đã cấp huy hiệu.','success');}catch(error){toast(error.message,'error');}};list.appendChild(row);});}

async function loadAdminCourses(){var courses=assertApi(await gas('adminGetCourseStructure',state.token)),students=assertApi(await gas('adminListStudents',state.token,{})),root=document.getElementById('view-root'),fragment=template('admin-courses-template');root.innerHTML='';root.appendChild(fragment);state.adminCourses=courses;state.adminStudents=students;renderCourseTree(courses);setupCourseEntityForm(root,courses);setupEnrollForm(root,courses,students);}
function optionHtml(value,label){return'<option value="'+esc(value)+'">'+esc(label)+'</option>';}
function fillSelect(select,items,valueKey,labelKey,empty){select.innerHTML=empty?'<option value="">'+esc(empty)+'</option>':'';items.forEach(function(item){select.insertAdjacentHTML('beforeend',optionHtml(item[valueKey],item[labelKey]));});}
function flattenLevels(courses){var out=[];courses.forEach(function(course){course.levels.forEach(function(level){out.push({levelId:level.levelId,levelName:course.courseName+' / '+level.levelName,courseId:course.courseId});});});return out;}
function flattenModules(courses){var out=[];courses.forEach(function(course){course.levels.forEach(function(level){level.modules.forEach(function(module){out.push({moduleId:module.moduleId,moduleName:course.courseName+' / '+level.levelName+' / '+module.moduleName,levelId:level.levelId});});});});return out;}
function renderCourseTree(courses){var tree=document.getElementById('admin-course-tree');tree.innerHTML='';courses.forEach(function(course){var node=document.createElement('div');node.className='course-tree-node';node.innerHTML='<div class="tree-course-title"><div><strong>'+esc(course.courseName)+'</strong><small>'+esc(course.courseId)+' · '+esc(course.status||'ACTIVE')+'</small></div><button class="ghost-button" data-edit-course="'+esc(course.courseId)+'">Sửa</button></div>';course.levels.forEach(function(level){node.insertAdjacentHTML('beforeend','<div class="tree-level"><div class="tree-row"><strong>'+esc(level.levelName)+'</strong><button class="ghost-button" data-edit-level="'+esc(level.levelId)+'">Sửa</button></div><small>'+esc(level.levelId)+'</small>'+level.modules.map(function(module){return'<div class="tree-module"><div class="tree-row"><strong>'+esc(module.moduleName)+'</strong><button class="ghost-button" data-edit-module="'+esc(module.moduleId)+'">Sửa</button></div><small>'+esc(module.moduleId)+'</small>'+module.lessons.map(function(lesson){return'<div class="tree-lesson"><div class="tree-row">'+esc(lesson.lessonName)+' · '+lesson.xpReward+' XP <button class="ghost-button" data-edit-lesson="'+esc(lesson.lessonId)+'">Sửa</button></div><small>'+esc(lesson.lessonId)+(lesson.requiresSubmission?' · cần nộp bài':'')+'</small></div>';}).join('')+'</div>';}).join('')+'</div>');});tree.appendChild(node);});if(!courses.length)tree.innerHTML='<p>Chưa có khóa học.</p>';tree.querySelectorAll('[data-edit-course],[data-edit-level],[data-edit-module],[data-edit-lesson]').forEach(function(button){button.onclick=function(){prefillCourseForm(button);};});}
function findCourseEntity(type,id){var found=null;(state.adminCourses||[]).some(function(course){if(type==='COURSE'&&course.courseId===id){found=course;return true;}return course.levels.some(function(level){if(type==='LEVEL'&&level.levelId===id){found=level;found.courseId=course.courseId;return true;}return level.modules.some(function(module){if(type==='MODULE'&&module.moduleId===id){found=module;found.levelId=level.levelId;return true;}return module.lessons.some(function(lesson){if(type==='LESSON'&&lesson.lessonId===id){found=lesson;found.moduleId=module.moduleId;return true;}return false;});});});});return found;}
function prefillCourseForm(button){var form=document.getElementById('course-entity-form'),type='COURSE',id=button.dataset.editCourse;if(button.dataset.editLevel){type='LEVEL';id=button.dataset.editLevel;}if(button.dataset.editModule){type='MODULE';id=button.dataset.editModule;}if(button.dataset.editLesson){type='LESSON';id=button.dataset.editLesson;}var item=findCourseEntity(type,id);if(!item)return;form.elements.entityType.value=type;form.elements.entityId.value=id;updateCourseParentFields(form);form.elements.name.value=item.courseName||item.levelName||item.moduleName||item.lessonName||'';form.elements.description.value=item.description||'';form.elements.sortOrder.value=item.sortOrder||1;form.elements.xpReward.value=item.xpReward||0;form.elements.contentHtml.value=item.contentHtml||'';form.elements.youtubeUrl.value=item.youtubeUrl||'';form.elements.requiresSubmission.checked=Boolean(item.requiresSubmission);if(type==='LEVEL')form.elements.courseId.value=item.courseId||'';if(type==='MODULE')form.elements.levelId.value=item.levelId||'';if(type==='LESSON')form.elements.moduleId.value=item.moduleId||'';form.scrollIntoView({behavior:'smooth',block:'start'});}
function setupCourseEntityForm(root,courses){var form=root.querySelector('#course-entity-form'),levels=flattenLevels(courses),modules=flattenModules(courses);fillSelect(form.elements.courseId,courses,'courseId','courseName','Chọn khóa học');fillSelect(form.elements.levelId,levels,'levelId','levelName','Chọn Level');fillSelect(form.elements.moduleId,modules,'moduleId','moduleName','Chọn Module');function refresh(){updateCourseParentFields(form);}form.elements.entityType.onchange=refresh;root.querySelector('#new-course-button').onclick=function(){form.reset();form.elements.entityType.value='COURSE';refresh();};refresh();form.onsubmit=saveCourseEntity;}
function updateCourseParentFields(form){var type=form.elements.entityType.value;form.querySelectorAll('.parent-field').forEach(function(label){label.classList.add('hidden');});form.elements.courseId.closest('label').classList.toggle('hidden',type!=='LEVEL');form.elements.levelId.closest('label').classList.toggle('hidden',type!=='MODULE');form.elements.moduleId.closest('label').classList.toggle('hidden',type!=='LESSON');}
function setupEnrollForm(root,courses,students){var form=root.querySelector('#enroll-form');fillSelect(form.elements.courseId,courses,'courseId','courseName','Chọn khóa học');fillSelect(form.elements.userId,students,'userId','fullName','Chọn học viên');form.onsubmit=async function(event){event.preventDefault();var button=form.querySelector('button'),values=Object.fromEntries(new FormData(form).entries());setButtonBusy(button,true);try{assertApi(await gas('adminEnrollStudentInCourse',state.token,values));toast('Đã gán học viên vào khóa học.','success');}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}};}
async function saveCourseEntity(event){event.preventDefault();var form=event.currentTarget,values=Object.fromEntries(new FormData(form).entries()),type=values.entityType,payload={description:values.description,status:'ACTIVE'};var idFields={COURSE:'courseId',LEVEL:'levelId',MODULE:'moduleId',LESSON:'lessonId'},nameFields={COURSE:'courseName',LEVEL:'levelName',MODULE:'moduleName',LESSON:'lessonName'};if(values.entityId)payload[idFields[type]]=values.entityId;payload[nameFields[type]]=values.name;if(type==='LEVEL')payload.courseId=values.courseId;if(type==='MODULE')payload.levelId=values.levelId;if(type==='LESSON')payload.moduleId=values.moduleId;if(type!=='COURSE'){payload.sortOrder=Number(values.sortOrder)||1;}if(type==='MODULE')payload.isRequired=true;if(type==='LESSON'){payload.contentHtml=values.contentHtml;payload.youtubeUrl=values.youtubeUrl;payload.resourceUrl='';payload.checklistJson='[]';payload.requiresSubmission=form.elements.requiresSubmission.checked;payload.xpReward=Number(values.xpReward)||0;}var button=form.querySelector('button');setButtonBusy(button,true);try{assertApi(await gas('adminSaveCourseEntity',state.token,type,payload));toast('Đã lưu nội dung.','success');form.reset();loadAdminCourses();}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}}

async function loadAdminPlatforms(){var data=assertApi(await gas('adminGetPlatformSettings',state.token)),root=document.getElementById('view-root'),fragment=template('admin-platforms-template'),form=fragment.querySelector('#platform-settings-form'),preview=fragment.querySelector('#admin-platform-preview');var groups={system:'Cấu hình hệ thống',platform:'Nền tảng cộng đồng / traffic'};Object.keys(groups).forEach(function(group){var fieldset=document.createElement('fieldset');fieldset.className='settings-group';fieldset.innerHTML='<legend>'+esc(groups[group])+'</legend>';data.items.filter(function(item){return item.type===group;}).forEach(function(item){var label=document.createElement('label');label.innerHTML='<span>'+esc(item.label)+(item.public?' <small>public</small>':' <small>admin only</small>')+'</span><input name="'+esc(item.key)+'" placeholder="'+esc(item.placeholder||'')+'" value="'+esc(item.value||'')+'">';fieldset.appendChild(label);});form.appendChild(fieldset);});form.insertAdjacentHTML('beforeend','<button class="primary-button" type="submit">Lưu Kênh & API</button>');renderPlatformLinks(preview,data.items,false);form.onsubmit=async function(event){event.preventDefault();var button=form.querySelector('button[type="submit"]'),values=Object.fromEntries(new FormData(form).entries());setButtonBusy(button,true);try{var result=assertApi(await gas('adminSavePlatformSettings',state.token,{values:values}));state.platforms=(result.items||[]).filter(function(item){return item.public;});toast('Đã lưu cấu hình.','success');loadAdminPlatforms();}catch(error){toast(error.message,'error');}finally{setButtonBusy(button,false);}};root.innerHTML='';root.appendChild(fragment);}

document.addEventListener('DOMContentLoaded',bootstrap);
})();
